version: '3'
services:
  app:
    container_name: frontend
    build: .
    ports:
      - "8080:80"

  nginx:
    image: nginx:alpine
    container_name: nginx-frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app